import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
    extend: {
      colors: {
        background: "var(--background)",
        surface: "var(--surface)",
        card: "var(--card)",
        "primary-text": "var(--primary-text)",
        "secondary-text": "var(--secondary-text)",
        "accent-orange": "var(--accent-orange)",
        "accent-blue": "var(--accent-blue)",
        "accent-warm": "var(--accent-warm)",
        "accent-warm-light": "var(--accent-warm-light)",
        "accent-purple": "var(--accent-purple)",
        "accent-pink": "var(--accent-pink)",
        "accent-green": "var(--accent-green)",
        "accent-coral": "var(--accent-coral)",
        "sky-deep": "var(--sky-deep)",
        "sky-top": "var(--sky-top)",
        "sky-mid": "var(--sky-mid)",
        "sky-light": "var(--sky-light)",
        "sky-pale": "var(--sky-pale)",
        "cloud-white": "var(--cloud-white)",
        "cloud-body": "var(--cloud-body)",
        "cloud-shadow": "var(--cloud-shadow)",
        "cloud-soft": "var(--cloud-soft)",
        "land-mist": "var(--land-mist)",
        "land-sage": "var(--land-sage)",
        "land-warm": "var(--land-warm)",
        "land-slate": "var(--land-slate)",
        "land-ground": "var(--land-ground)",
        "land-runway": "var(--land-runway)",
        "tarmac-base": "var(--tarmac-base)",
        "tarmac-soft": "var(--tarmac-soft)",
        "tarmac-edge": "var(--tarmac-edge)",
        "sunrise-warm": "var(--sunrise-warm)",
        border: "var(--border)",
        "border-light": "var(--border-light)",
        glow: "var(--glow)",
      },
      fontFamily: {
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        heading: ["var(--font-heading)", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        display: ["var(--font-display)", "sans-serif"],
        accent: ["var(--font-accent)", "serif"],
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
        "30": "7.5rem",
        "34": "8.5rem",
        "38": "9.5rem",
        "42": "10.5rem",
        "50": "12.5rem",
        "60": "15rem",
        "72": "18rem",
        "84": "21rem",
        "96": "24rem",
      },
      letterSpacing: {
        "hero": "0.1em",
        "label": "0.14em",
      },
      lineHeight: {
        "body": "1.75",
      },
      fontSize: {
        "hero": "clamp(64px, 10vw, 130px)",
      },
      borderRadius: {
        "card": "24px",
        "cartoon": "24px",
        "bubble": "30px",
      },
      borderWidth: {
        "3": "3px",
        "cartoon": "3px",
      },
      boxShadow: {
        "cartoon": "4px 4px 0px var(--cartoon-shadow)",
        "cartoon-lg": "6px 6px 0px var(--cartoon-shadow)",
        "cartoon-sm": "2px 2px 0px var(--cartoon-shadow)",
        "cartoon-hover": "6px 8px 0px var(--cartoon-shadow)",
        "cartoon-active": "1px 1px 0px var(--cartoon-shadow)",
        "cartoon-orange": "4px 4px 0px #C56200",
        "cartoon-blue": "4px 4px 0px #006064",
        "cartoon-green": "4px 4px 0px #1B5E20",
        "cartoon-pink": "4px 4px 0px #880E4F",
      },
      backdropBlur: {
        "nav": "12px",
      },
      transitionDuration: {
        "400": "400ms",
        "600": "600ms",
        "1200": "1200ms",
      },
      animation: {
        "glow-pulse": "glow-pulse 2.5s ease-in-out infinite",
        "blink-green": "blink-green 1s infinite",
        "status-pulse-blue": "status-pulse-blue 2s infinite",
        "status-pulse-orange": "status-pulse-orange 1.2s infinite",
        "scroll-bounce": "scroll-bounce 2s ease-in-out infinite",
        "marquee": "marquee 20s linear infinite",
        "marquee-mobile": "marquee 12s linear infinite",
        "wiggle": "wiggle 1.5s ease-in-out infinite",
        "bounce-gentle": "bounce-gentle 2s ease-in-out infinite",
        "bounce-cartoon": "bounce-cartoon 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "pop-in": "pop-in 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "wobble": "wobble 3s ease-in-out infinite",
      },
      keyframes: {
        "glow-pulse": {
          "0%, 100%": { boxShadow: "4px 4px 0px var(--cartoon-shadow)" },
          "50%": { boxShadow: "4px 4px 0px var(--cartoon-shadow), 0 0 20px 4px rgba(255, 140, 0, 0.3)" },
        },
        "blink-green": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "status-pulse-blue": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.6", transform: "scale(1.1)" },
        },
        "status-pulse-orange": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.6", transform: "scale(1.1)" },
        },
        "scroll-bounce": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(10px)" },
        },
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-33.333%)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px) rotate(-1deg)" },
          "50%": { transform: "translateY(-12px) rotate(2deg)" },
        },
        "wiggle": {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        "bounce-gentle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "bounce-cartoon": {
          "0%": { transform: "scale(0.3)", opacity: "0" },
          "50%": { transform: "scale(1.08)" },
          "70%": { transform: "scale(0.95)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "pop-in": {
          "0%": { transform: "scale(0)", opacity: "0" },
          "60%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "wobble": {
          "0%, 100%": { transform: "rotate(0deg)" },
          "25%": { transform: "rotate(1deg)" },
          "75%": { transform: "rotate(-1deg)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
